language: node_js
node_js:
  - v9
  - v8
  - v6
before_script: 
  - npm run-script pretest
run_script:
  - npm run-script test
after_script: cat ./node_modules/lcov-parse/coverage/lcov.info | ./node_modules/.bin/coveralls
